---
.github/workflows/ci.yml:
  matrix_command: yq -o=json build_versions.yaml | jq -c
  matrix_requires_yq: true
  build_file: Dockerfile
  image_tag: 'ci/test:${{ matrix.puppet_release }}'
  build_args:
    - 'BASE_IMAGE=${{ matrix.base_image }}'
  dependabot_automerge: false
  save_pr_number: true
